export const checkBasicProps = (prop: string) => {
    const basicProps = [
        'contract',
        'seller',
        'agent',
        'vessel',
        'transport',
        'agreementNo',
        'invoice',
        'date',
        'blMode',
        'blNo',
        'portFrom',
        'terms',
        'portTo',
        'consignee',
        'msc',
        'product',
        'sort',
        'pack',
        'places',
        'placesTotal',
        'price',
        'priceTotal',
        'id',
        'operationUseless',
        'reice',
        'konosament',
        'company',
        'operation',
        'client',
        'contractNo',
        'contractDate',
        'bank',
        'deliveryDate',
        'paymentDate',
    ];

    return basicProps.includes(prop);
};
